// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOcg_5o0vasNME7-J-UiTL3eCLf-yXE34',
    appId: '1:519126061927:web:6175faaba6ed8a0d1295c2',
    messagingSenderId: '519126061927',
    projectId: 'chat-app-90bf6',
    authDomain: 'chat-app-90bf6.firebaseapp.com',
    storageBucket: 'chat-app-90bf6.appspot.com',
    measurementId: 'G-3R61LCGHE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjrwiIZq8lVNJLtlzRCBllGzLVedQmyr4',
    appId: '1:519126061927:android:ef95d489e585e0dc1295c2',
    messagingSenderId: '519126061927',
    projectId: 'chat-app-90bf6',
    storageBucket: 'chat-app-90bf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3w-VylwIXD-jQApixu6WZ5UT8tHDC6Gg',
    appId: '1:519126061927:ios:2c7e8dd847c234901295c2',
    messagingSenderId: '519126061927',
    projectId: 'chat-app-90bf6',
    storageBucket: 'chat-app-90bf6.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3w-VylwIXD-jQApixu6WZ5UT8tHDC6Gg',
    appId: '1:519126061927:ios:9e4cc9c5a348402a1295c2',
    messagingSenderId: '519126061927',
    projectId: 'chat-app-90bf6',
    storageBucket: 'chat-app-90bf6.appspot.com',
    iosBundleId: 'com.example.practice.RunnerTests',
  );
}
